#### EXECUTE ON GOOGLE COLAB

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/sample_data/fake_train.csv", header=0)

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
# from google.colab import drive
# drive.mount('/content/drive')

In [5]:
df.columns

Index(['id', 'title', 'author', 'text', 'label'], dtype='object')

In [6]:
df.shape

(20800, 5)

In [7]:
df.dropna(inplace=True)

In [8]:
df.shape

(18285, 5)

In [9]:
X=df.drop('label',axis=1)

In [10]:
X.shape

(18285, 4)

In [11]:
y=df['label']

In [12]:
y.shape

(18285,)

In [13]:
!pip install tensorflow

In [14]:
# pip show tensorflow

In [15]:
# import sys
# print(sys.executable)

In [16]:
!pip install keras

In [17]:
import tensorflow as tf

In [18]:
tf.__version__

'2.18.0'

In [19]:
# from tensorflow.keras.layers import Embedding, LSTM, Dense
# from tensorflow.keras.preprocessing.sequence import pad_sequence
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.preprocessing.text import one_hot

In [20]:
from tensorflow import keras

In [21]:
from keras.layers import Embedding, LSTM, Dense, Dropout

In [22]:
from keras.preprocessing.sequence import pad_sequences

In [23]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [24]:
from keras.models import Sequential

In [25]:
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
voc_size=500

In [27]:
messages=X.copy()

In [28]:
messages.reset_index(inplace=True)

In [29]:
import nltk
import re
from nltk.corpus import stopwords

In [30]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [31]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [32]:
stemmer=PorterStemmer()
lemmatizer=WordNetLemmatizer()

In [33]:
corpus = []

for i in range(len(messages)):
    print(i)
    review = re.sub('[^a-z A-Z]',' ',messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [lemmatizer.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review = ' '.join(review)
    print(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
15785
speaker ryan obamacare lite plan primer breitbart
15786
choice trump oligarchy
15787
paul ryan call fact comey memo people want hurt president
15788
anti trump protester tool oligarchy
15789
next big shoe drop
15790
protester going trump hotel dc communist lunatic course
15791
way older people naturally improve health wellness
15792
watch gunfire rattle tehran drone buzz iranian capital
15793
question going need ask investment fee new york time
15794
lawsuit claim san francisco state university exhibit pattern anti jewish animus
15795
occupier david fry released jail really free
15796
wikileaks assange promise hillary arrest next release
15797
heal chakras increase personal development
15798
buzz aldrin ordered away moon
15799
know gummy candy really made
15800
high tax northern state ruining baseball
15801
donald trump peacenik president information
15802
biden hint u response russia cyberattacks new york time
15803
collage corr

In [34]:
corpus

['house dem aide even see comey letter jason chaffetz tweeted',
 'flynn hillary clinton big woman campus breitbart',
 'truth might get fired',
 'civilian killed single u airstrike identified',
 'iranian woman jailed fictional unpublished story woman stoned death adultery',
 'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart',
 'beno hamon win french socialist party presidential nomination new york time',
 'back channel plan ukraine russia courtesy trump associate new york time',
 'obama organizing action partner soros linked indivisible disrupt trump agenda',
 'bbc comedy sketch real housewife isi cause outrage',
 'russian researcher discover secret nazi military base treasure hunter arctic photo',
 'u official see link trump russia',
 'yes paid government troll social medium blog forum website',
 'major league soccer argentine find home success new york time',
 'well fargo chief abruptly step new york time',
 'anonymous donor pay 

In [35]:
## one hot representation

In [36]:
onehot_rep = [one_hot(words,voc_size) for words in corpus]
onehot_rep

[[422, 306, 484, 114, 469, 22, 391, 106, 317, 495],
 [417, 167, 316, 169, 237, 263, 158],
 [474, 150, 400, 226],
 [119, 169, 62, 274, 422, 171],
 [365, 237, 171, 376, 295, 259, 237, 320, 329, 130],
 [489, 208, 147, 489, 306, 69, 214, 80, 442, 8, 275, 219, 266, 161, 158],
 [196, 211, 424, 155, 164, 444, 277, 347, 23, 143, 58],
 [91, 452, 139, 327, 453, 278, 69, 434, 23, 143, 58],
 [333, 4, 404, 284, 344, 217, 400, 380, 69, 28],
 [208, 459, 423, 319, 182, 14, 77, 298],
 [12, 193, 278, 357, 33, 381, 175, 2, 292, 169, 41],
 [274, 200, 469, 35, 69, 453],
 [260, 90, 217, 414, 85, 236, 93, 237, 12],
 [412, 475, 111, 343, 156, 429, 267, 23, 143, 58],
 [319, 192, 385, 66, 283, 23, 143, 58],
 [272, 400, 75, 69, 184, 131, 109, 75, 32, 320],
 [224, 300, 167],
 [218, 353, 387, 65, 69, 233, 449, 158],
 [229, 266, 316, 78, 128, 14, 53, 392, 259],
 [367, 249, 69, 78, 8, 158],
 [462, 18, 63, 397, 416, 53, 74, 237, 29, 23, 143, 58],
 [478, 202, 449, 88, 120, 84, 452],
 [266, 241, 20, 287, 341, 54, 96, 3

In [37]:
## padding 0 -- pre

In [38]:
sent_length = 20
embedded_docs = pad_sequences(onehot_rep, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[  0   0   0 ... 106 317 495]
 [  0   0   0 ... 237 263 158]
 [  0   0   0 ... 150 400 226]
 ...
 [  0   0   0 ...  23 143  58]
 [  0   0   0 ... 466 147 497]
 [  0   0   0 ... 490 421 318]]


In [39]:
len(embedded_docs)

18285

In [40]:
## creating a simple LSTM Model

In [41]:
embedding_vector_features=40

model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
print(model.summary)

<bound method Model.summary of <Sequential name=sequential, built=False>>


In [42]:
len(embedded_docs),y.shape

(18285, (18285,))

In [43]:
import numpy as np

X_final=np.array(embedded_docs)
y_final=np.array(y)

In [44]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [47]:
model.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10, batch_size=64)

Epoch 1/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.7827 - loss: 0.4344 - val_accuracy: 0.8974 - val_loss: 0.2326
Epoch 2/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.9085 - loss: 0.2165 - val_accuracy: 0.9006 - val_loss: 0.2272
Epoch 3/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9116 - loss: 0.2116 - val_accuracy: 0.8999 - val_loss: 0.2316
Epoch 4/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9133 - loss: 0.2092 - val_accuracy: 0.9001 - val_loss: 0.2306
Epoch 5/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9194 - loss: 0.1962 - val_accuracy: 0.9074 - val_loss: 0.2197
Epoch 6/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9245 - loss: 0.1827 - val_accuracy: 0.9079 - val_loss: 0.2205
Epoch 7/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9334 - loss: 0.1674 - val_accuracy: 0.9054 - val_loss: 0.2207
Epoch 8/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9358 - loss: 0.1618 - val_a

In [48]:
y_train_pred = (model.predict(X_train)>0.5).astype("int32")

383/383 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step


In [49]:
y_test_pred = (model.predict(X_test)>0.5).astype("int32")

189/189 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step


In [50]:
type(y_test), type(y_test_pred)

(numpy.ndarray, numpy.ndarray)

In [51]:
len(y_test), len(y_test_pred)

(6035, 6035)

In [52]:
y_test.shape, y_test_pred.shape

((6035,), (6035, 1))

In [53]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [54]:
conf_mat = confusion_matrix(y_test, y_test_pred)
conf_mat

array([[3056,  363],
       [ 245, 2371]])

In [55]:
class_rep = classification_report(y_test, y_test_pred)
print(class_rep)

              precision    recall  f1-score   support

           0       0.93      0.89      0.91      3419
           1       0.87      0.91      0.89      2616

    accuracy                           0.90      6035
   macro avg       0.90      0.90      0.90      6035
weighted avg       0.90      0.90      0.90      6035



In [56]:
model_accuracy = accuracy_score(y_test, y_test_pred)
model_accuracy

0.8992543496271748

In [57]:
## Enhance the model by adding Dropout

In [58]:
embedding_vector_features=40

model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
print(model.summary)

<bound method Model.summary of <Sequential name=sequential_1, built=False>>


In [59]:
model.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10, batch_size=64)

Epoch 1/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.7697 - loss: 0.4516 - val_accuracy: 0.8949 - val_loss: 0.2430
Epoch 2/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9038 - loss: 0.2273 - val_accuracy: 0.8978 - val_loss: 0.2384
Epoch 3/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9084 - loss: 0.2155 - val_accuracy: 0.9007 - val_loss: 0.2302
Epoch 4/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 11s 51ms/step - accuracy: 0.9076 - loss: 0.2124 - val_accuracy: 0.9011 - val_loss: 0.2278
Epoch 5/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9147 - loss: 0.2006 - val_accuracy: 0.9032 - val_loss: 0.2260
Epoch 6/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9220 - loss: 0.1928 - val_accuracy: 0.9069 - val_loss: 0.2217
Epoch 7/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9244 - loss: 0.1843 - val_accuracy: 0.9054 - val_loss: 0.2233
Epoch 8/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9322 - loss: 0.1691 - va

In [60]:
y_train_pred = (model.predict(X_train)>0.5).astype("int32")

383/383 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step


In [61]:
y_test_pred = (model.predict(X_test)>0.5).astype("int32")

189/189 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step


In [62]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [63]:
conf_mat = confusion_matrix(y_test, y_test_pred)
conf_mat

array([[3068,  351],
       [ 241, 2375]])

In [64]:
class_rep = classification_report(y_test, y_test_pred)
print(class_rep)

              precision    recall  f1-score   support

           0       0.93      0.90      0.91      3419
           1       0.87      0.91      0.89      2616

    accuracy                           0.90      6035
   macro avg       0.90      0.90      0.90      6035
weighted avg       0.90      0.90      0.90      6035



In [65]:
model_accuracy = accuracy_score(y_test, y_test_pred)
model_accuracy

0.9019055509527755